### ISSUE TITLE
Server is slow !

### ISSUE THREAD

**Issue by frague59** [alchemy-fr/Phraseanet#1788]
Hi, 

I'm installing phraseanet on a fresh debian jessie server, but I can see slowness on the admin interface : the system takes about 90 seconds to display the "Connected Users" page, event if I'm the only people connected.
When changing view, it takes many time too. 
I'm the server admin, so I can perform some actions on it, to speed it up. The server is quite comfortable, with 8 Gio of RAM, and 2 procs. 

Settings : 
* debian 8.3
* maraidb 10.0
* apache 2.4.10
* php 5.6.17
* phraseanet 3.8.8

Thanks for your help !

**Comment by moctardiouf** [comment]
Hi,
we invite you to post your support requests on our Google groups

    phrasea-support-en@googlegroups.com (Usage support)

    phrasea-install-en@googlegroups.com ( Installation support)

    phrasea-devel@googlegroup.com (development support)

Best Regards

Moctar Diouf

Phraseanet Team
