### ISSUE TITLE
Substitution en quarantaine

### ISSUE THREAD

**Issue by Philippe-M** [alchemy-fr/Phraseanet#1995]
J'upload un fichier une 1ere fois qui est validé, je l'upload à nouveau. Il m'est dit que le nouveau est mis en quarantaine.

Je vais voir effectivement il y est, je clic sur le bouton substituer mais rien ne se passe. Alors que si je clic sur Ajouter ou Supprimer l'action est ok.

Je test avec la VM mise à jour par update_phraseanet.sh ce matin.

**Comment by pnrm** [comment]
Bonjour,
J'ai le même problème avec la version 4.02 de phraseanet, php 7 debian 9
