### ISSUE TITLE
Fix Facebook SDK package name in composer.json

### ISSUE THREAD

**Issue by o1y** [alchemy-fr/Phraseanet#2069]
The repository [facebook/php-sdk](https://packagist.org/packages/facebook/php-sdk) is no longer maintained and won't provide the required version `~4.0.1`, which is configured in [composer.json](https://github.com/alchemy-fr/Phraseanet/blob/master/composer.json#L59).

Composer fails with the following error:
`The requested package facebook/php-sdk ~4.0.1 exists as facebook/php-sdk[dev-master, v3.2.0, v3.2.1, v3.2.2, v3.2.3] but these are rejected by your constraint.`

Solution: change the packagename to [facebook/graph-sdk](https://packagist.org/packages/facebook/graph-sdk)

**Comment by nmaillat** [comment]
Done
