### ISSUE TITLE
Task manager ne se lance pas

### ISSUE THREAD

**Issue by NikoTesla** [alchemy-fr/Phraseanet#2461]
Bonjour,
OS : Debian jessie 64 bits
install et ses dépendances ok, tout fonctionne sauf le lancement des taches depuis l'interface web ou en CLI 
phraseanet.ERROR: Unable to notify the task manager with message "information" within timeout of 2 seconds {"exception":"[object] (ZMQSocketException(code: 156384763): Failed to send message: Operation cannot be accomplished in current state at /var/www/Phraseanet/lib/Alchemy/Phrasea/TaskManager/Notifier.php:57)"} {"url":"/admin/task-manager/live"
Du coup je n'ai pas les thumbs dans la prod, car la tache de création des sous definitions ne se lance pas.

**Comment by flody** [comment]
Hello,

Is there any news about this issue or did you find a solution? I have the same problem here.

**Comment by nmaillat** [comment]
Hello, sorry for the late answer, this issue is fix with this PR 

https://github.com/alchemy-fr/Phraseanet/pull/2704

Nicolas
