### ISSUE TITLE
Graphic mode installation error

### ISSUE THREAD

**Issue by lloonngg** [alchemy-fr/Phraseanet#2807]
Hi,

I am setting  up Phraseanet 4.0.3 in docker and have gotten to the graphic mode installation step.  I was able to connect to my databases and elasticsearch; however, during installation there is an error:

an error occured: Databox template "en\x2Dsimple" not found.

Could you help fix this error?  Where can I find the missing Databox template?  I downloaded the Phraseanet package directly from:  https://www.phraseanet.com/builds/alchemy-fr-Phraseanet-v4.0.3.zip.

Thanks,

Long

**Comment by nmaillat** [comment]
Hello, 
Sorry We don't reproduce your issue.

You can check if you if the model is present in 
/lib/conf.d/data_templates/
ex: en-simple.xml

Do you have the same issue with command tools install.
 bin/setup system:install

What is the result of 
 bin/setup check:system

We close this issue, send you answer to the google group.
With more info about linux version use.

https://groups.google.com/forum/#!forum/phrasea-install-en


thank 

Nicolas
