### ISSUE TITLE
thumbnail image are very small even for big resolution images

### ISSUE THREAD

**Issue by mdemori** [alchemy-fr/Phraseanet#3281]
The thumbnail size is really small even for very hig res images.
I need bigger thumbnail size, how can I change the resolution/size?

I already try to set  

user-settings:
             images_size: 320
             editing_image_size: 640

but seem that don't work.. :(

Below an example of what appen with an image that has an original resolution of 10109x4542 at 300dpi
![image](https://user-images.githubusercontent.com/2266315/71163104-b6536900-224c-11ea-8ef4-06e4ef08b8e6.png)

below all information about the original image
![image](https://user-images.githubusercontent.com/2266315/71163139-c66b4880-224c-11ea-8f49-596217684bab.png)

**Comment by moctardiouf** [comment]
Hi, 
an option of the Phraseanet's sub-view creation task extracts embedded thumbnails.
You can deactivate it.

![image](https://user-images.githubusercontent.com/1235702/73192777-d61e5c80-4129-11ea-9a21-2301496e9029.png)

regards
