### ISSUE TITLE
Picture does not appear correctly in Production

### ISSUE THREAD

**Issue by Simonakava** [alchemy-fr/Phraseanet#3290]
When I want to upload an image, it does not appear correctly in the Production interface. The problem is that the upload works but it's always the same random picture that appears in the Production interface. I use Firefox 72.0.1 (64 bits)
![Capture_ecran_pb_upload_phraseanet](https://user-images.githubusercontent.com/28387526/72328246-dd1d8780-36b2-11ea-8c25-0fbb5a55502e.PNG)

**Comment by moctardiouf** [comment]
Hello You need to run the Phraseanet task-manager

see : https://docs.phraseanet.com/4.0/en/Admin/TaskManager.html

Regards.
