### ISSUE TITLE
Docker deployment without building

### ISSUE THREAD

**Issue by weidi** [alchemy-fr/Phraseanet#3644]
Hi,

just trying to understand why i need to build all the containers when deploying Phraseanet.
Actually i tried to just remove the build part from the compose file but that doesn't work either.
Shouldn't it be that a container by itself is immutable and only controlled via ARGs or other external things to be reproducible?

**Comment by nmaillat** [comment]
Hello, 
Phraseanet have some external dependencies (MariaDB, Elasticsearch, Redis, RabbitMQ), and cannot run without these dependencies.
Check ```.env file``` (https://github.com/alchemy-fr/Phraseanet#get-started) for customizing your phraseanet instance.
Our docker-compose provides the pre-requisite dependencies and make a fresh installation of Phraseanet (for run or dev).
You can also migrate your data from another Phraseanet by importing existing databases in MariaDB and configuration file in config/configuration.yml 

If you don't want to build images, you can pull our images from Docker Hub.

https://hub.docker.com/r/alchemyfr/phraseanet-fpm 
https://hub.docker.com/r/alchemyfr/phraseanet-worker
https://hub.docker.com/r/alchemyfr/phraseanet-nginx
https://hub.docker.com/r/alchemyfr/phraseanet-db
https://hub.docker.com/r/alchemyfr/phraseanet-elasticsearch

**Comment by weidi** [comment]
Hi @nmaillat,

i tried with just using the images from docker hub.
Removed all build commands from the docker-compose.yml and changed the .env.
It seems to run but nginx gives me "Bad Gateway"

BR

**Comment by nmaillat** [comment]
Hi you just need to pull image from docker-hub, not need to remove build section from Dockerfile.

Concerning the .env 
keep in mind .env is versioned and for override .env value, you can follow the method describe in Phraseanet README
https://github.com/alchemy-fr/Phraseanet#using-a-envlocal-custom-env 
 
What the matter if you try to restart the nginx container ?

**Comment by weidi** [comment]
But that would require to pull the images manually.
When configuring the .env and removing build directives it kind of works but still not the expected results.
From the README there is this section, but even configuring the docker registry and a tag it still runs off to build. So this is not an or but a must.

> To use them and not build the images locally, we advise to override the properties in file: env.local

> # Registry from where you pull Docker images
> PHRASEANET_DOCKER_REGISTRY=alchemyfr
> # Tag of the Docker images
> PHRASEANET_DOCKER_TAG=
> or
> 
> Pull images before launch docker-compose

Also what I am trying to do is only getting the composefile and .env and let docker compose pull all requirements but right now the folder structure that is created will stay empty (and therefore my nginx has no files to work on).
From the principles of a container it would make more sense to pull the containers and they bring the required files and folder structure and not having the need to pull the "outside" repository with files and folders.

That has the advantage that there is no problem with the env.local and compose override but just a clean way to start.

**Comment by nmaillat** [comment]
Hello, Please keep in mind that the provided deployment is dev and test oriented.
Here you can find an alternative deployment which can be used without cloning Phraseanet code repository.
https://github.com/alchemy-fr/phraseanet-docker
Although this deployment is NOK at this time, he may help you to write your own deployment and understand which sharing volumes Phraseanet are needed.
Some files are generated by Phraseanet and worker containers (fpm/php) but served by gateway (nginx) container.
You can also make a PR on Phraseanet-docker deployment to fix it 
Thanks, Best Regards

**Comment by weidi** [comment]
Thank you for the comment, created a minimal docker-compose deployment now that is only meant for prod usage. Will make a pull request in the phraseanet-docker repo therefore closing this issue. 
Thank you!
