### ISSUE TITLE
Search in prod view redirects to login page 

### ISSUE THREAD

**Issue by frague59** [alchemy-fr/Phraseanet#3651]
Hi, 

I'm connected to my newly upgraded Phraseanet 4.1, with an admin account.

The elasticsearch instance is fully populated, but no records are returned by search.

When debugging in my browser, I can see a 302 (Redirection) response on HTTP request to `/prod/query` to the login page,

**Comment by frague59** [comment]
I's weird... The search engine works on a MS Edge or Chromium instance but not in Firefox. 
I've tryed to delete cookies, but it not fix the issue...

**Comment by frague59** [comment]
It seems that no cookies are sent by jQuery on Firefox, which explains the redirection to the login page. 

# In firefox (tested in 78 ESR, 82  and 83 DEV)

Here the headers for the /prod/query/ request:
```
POST /prod/query/ HTTP/1.1
Host: media.tourcoing.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Content-Length: 1418
Origin: https://media.tourcoing.fr
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Response headers, with Location set as redirection target: 
```
HTTP/1.1 302 Found
Date: Tue, 17 Nov 2020 13:27:57 GMT
Server: Apache/2.4.25 (Debian)
Set-Cookie: PHPSESSID=hzYWje39hz0%2CJkvPnXOX3epJFZ2; path=/; secure
X-Phraseanet-End-Session: 1
Cache-Control: no-cache
Location: /login/?redirect=../prod/query/
Set-Cookie: locale=fr; path=/
Content-Length: 368
Content-Type: application/json
Content-Security-Policy: upgrade-insecure-requests
Set-Cookie: media=orbcomm; path=/
```
I've tried various settings in Firefox, about security, without any results.

**Comment by moctardiouf** [comment]
Hello,

it seems like you are behind a firewall or a reverse proxy that may be exposes your ssl certificate.
If so you may need to add the firewall or proxy IP to Phraseanet configuration trusted proxies.

https://docs.phraseanet.com/4.1/fr/Admin/Configuration.html?highlight=trusted

Best regards

**Comment by moctardiouf** [comment]
Have you also activated the php session.cookie_secure in php.ini

**Comment by frague59** [comment]
Hi, 

Thanks for your answers ! 

The front HAProxy provides a *.exanple.com certificate for all domains served by the internal apps of my organization.
I've set the trusted-proxies with the front HAProxy IP address, at the root of the config file: 

```sh
cat config/configuration.yml
...
trusted-proxies:
    - 172.18.3.212
...
```
**This does not work for now.**

 While exploring the JS stack of the application, I've noted the /prod/query/ query uses a full URL address, and sends it to a `http://` address, not a `https://` -- This could explains the redirection.
 
The url comes from a `serviceConfig` object in production.js file, I don't know how it's build and where it comes from.

**Comment by moctardiouf** [comment]
Hello
After you added your ha-proxy Ip have you ran
Bon/console compile:configuration

Have you disconnected and reconnected?
What is the ip into the admin module associated to you session different
from the proxy one !

Regards

Le mar. 17 nov. 2020 à 16:03, François GUÉRIN <notifications@github.com> a
écrit :

**Comment by frague59** [comment]
OK, 
Sorry, I did not use the right IP for the HAProxy...
I've set the in php.ini:
```
session.cookie_secure = 1
```

I've disconnected and reconnect to a new session, my IP is now presented in the session list, but I sill have no image in the PROD view, with the same redirection to the login page. Note that my server has no https enabled internally

I've tried to hack the query mechanism, and set in www/assets/production/production.min.js:62787
```javascript
url = "/"
```
In that case, the images are loaded...

How is determined the schema (http://) in the URL provided in the serviceConfig object ? Maybe I could patch this to use '/' as default url ?

Thanks for your help !

**Comment by moctardiouf** [comment]
Hello When you are behind a proxy and set it as trusted proxies we uses the header X-Forwarded-Proto

Exemple conf on ha-proxy

    http-request set-header X-Forwarded-Port %[dst_port]
    http-request add-header X-Forwarded-Proto https if { ssl_fc }

https://www.haproxy.com/fr/documentation/aloha/12-0/traffic-management/lb-layer7/http-rewrite/

Regards
