### ISSUE TITLE
Container 'phraseanet_phraseanet_1' keeps restarting after `docker-compose`

### ISSUE THREAD

**Issue by AdamJel** [alchemy-fr/Phraseanet#3708]
Hello,

I am interested in the application for bussiness use and I want to test it in Docker first. After download and `docker-compose up -d`, all but one containers are up and running, but one container with name 'phraseanet_phraseanet_1' keeps restarting as seen in the picture:
![Docker-status](https://user-images.githubusercontent.com/33990009/106589370-3c636980-654c-11eb-9ce6-c7c69f111c8c.png)<br>

Log from this container is:
```
,-._.-._.-._.-._.-.

`-. ,-'

.----------------------------------------------. | |

| | | |

| Hello ! | | |

| | | |

| You are on your way to install Phraseanet, | ,';".________.-.

| You will need access to 2 MySQL databases. | ;';_' )]

| | ; `-|

| `. `T- |

`----------------------------------------------._ \ | |

`-; | |

|..________..-|

/\/ |________..|

,'`./ >,( |

\_.-|_/,-/ ii | |

`."' `-/ .-"""|| |

/`^"-; | ||____|

/ / `.__/ | ||

/ | ||

| ||
[Doctrine\DBAL\Exception\ConnectionException]
An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused
[Doctrine\DBAL\Driver\PDOException]
SQLSTATE[HY000] [2002] Connection refused
[PDOException]
SQLSTATE[HY000] [2002] Connection refused
system:install [--email [EMAIL]] [--password [PASSWORD]] [--db-host [DB-HOST]] [--db-port [DB-PORT]] [--db-user [DB-USER]] [--db-password [DB-PASSWORD]] [--appbox [APPBOX]] [--databox [DATABOX]] [--db-template [DB-TEMPLATE]] [--data-path [DATA-PATH]] [--server-name [SERVER-NAME]] [--es-host [ES-HOST]] [--es-port [ES-PORT]] [--es-index [ES-INDEX]] [--download-path [DOWNLOAD-PATH]] [--lazaret-path [LAZARET-PATH]] [--caption-path [CAPTION-PATH]] [--scheduler-locks-path [SCHEDULER-LOCKS-PATH]] [--worker-tmp-files [WORKER-TMP-FILES]] [-y|--yes] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command>
config/configuration.yml doesn't exist, entering setup...
+ '[' -z admin@alchemy.fr ']'
+ '[' -z 'iJRqXU0MwbyJewQLBbra6IWHsWly ' ']'
+ /var/alchemy/Phraseanet/bin/setup system:install --email=admin@alchemy.fr --password=iJRqXU0MwbyJewQLBbra6IWHsWly --db-host=db --db-port=3306 --db-user=root --db-password=root --db-template=DublinCore --appbox=ab_master --databox=db_databox1 --server-name=localhost --download-path=./datas/download --lazaret-path=./datas/lazaret --caption-path=./tmp/caption --worker-tmp-files=./tmp/worker --data-path=/var/alchemy/Phraseanet/datas -y
```

Could you advise me on how to procced? Thank you

**Comment by nmaillat** [comment]
Hello,
Check if don't have  mismatch in .env file between value 
`MYSQL_ROOT_PASSWORD= `
and 
`PHRASEANET_DB_PASSWORD= `
check also the network name of mysql service
`PHRASEANET_DB_HOST=`

Note if you start the stack with
`docker-compose up -d `
you launch the stack in dev mode, so the code are shared between your host and the docker container.

so for testing, this is better to run without code sharing. 

`docker-compose -f docker-compose.yml up -d `

`.env` is versioned so you can use this method for overriding env value 
https://github.com/alchemy-fr/Phraseanet#using-a-envlocal-custom-env

regards, Nicolas

**Comment by nmaillat** [comment]
you can also remove or rename `docker-compose.override.yml `file

**Comment by AdamJel** [comment]
Hi, thank you for suggestion.
- Parameters `MYSQL_ROOT_PASSWORD=` and `PHRASEANET_DB_PASSWORD=` are the same. 
- Parameter `PHRASEANET_DB_HOST=` is set to `PHRASEANET_DB_HOST=db`. Is that the correct value?
- I have these parameters set:
  - `export PHRASEANET_DOCKER_TAG=latest`
  - `export INSTALL_ACCOUNT_EMAIL=<email>`
  - `export INSTALL_ACCOUNT_PASSWORD=<pas>`
  - `export PHRASEANET_APP_PORT=8082`
- file `docker-compose.override.yml` is not present....

But it behaves the same way - container keeps restarting.. Any other thoughts?

**Comment by moctardiouf** [comment]
Hello, 
I suggest you make a `docker-composer down --volumes` and then after run `docker-compose -f docker-compose.yml up -d`.
I seems like the phraseanet_fpm allowed ip to connect on db have changed between two executions.

Regards

**Comment by AdamJel** [comment]
@moctardiouf  Hello, that got me to the firsterror log situation - not solving it.

**Comment by nmaillat** [comment]
@AdamJel hello , I have make a fresh install with packaged version https://www.phraseanet.com/builds/alchemy-fr-Phraseanet-v4.1.3.zip without issue. 

`phraseanet_1     | 
phraseanet_1     | Application-Box : Connection successful !
phraseanet_1     | Data-Box : Connection successful !
phraseanet_1     | `

I just need to restart the gateway container for avoid 502 bad gateway return by NGINX  because FPM process is launch after Phraseanet installation and Nginx check tho earlier.
We work on a fix for this  issue by introducing an `Healthcheck` directive  in Gateway container docker-compose.yml
`docker-compose restart gateway` container after the first `docker-compose up -d ` 
At the first up, if the phraseanet container don't find the config/configuration.yml the container made an installation  and 
 restarting until it can do. 
Nginx need to reload conf

**Comment by nmaillat** [comment]
@AdamJel In addition to my previous comment, we do not explicitly declare a network in docker-compose and we think this may have caused the issue you encountered. We are working on a fix by declaring a network in docker-compose for this end of the week.
 thanks for your reply
