### ISSUE TITLE
Small typo in German login page (Footer Link to main page)

### ISSUE THREAD

**Issue by tapwag** [alchemy-fr/Phraseanet#3757]
Dear developers,

I would like to address a typo in "Hautpseite Hilfe © Copyright Alchemy 2005-2021" - It should be "Hau**pt**seite" - p and t are in the wrong order.

**Comment by nmaillat** [comment]
Dear Mister, 
Thank you for your return, this is fixed today  in this commit 
https://github.com/alchemy-fr/Phraseanet/tree/727f745e5d35fc5636b2d83e7fa4f94f4febc28f
Best regards
