### ISSUE TITLE
Abandoned Docker repositories warning when starting Docker image

### ISSUE THREAD

**Issue by tapwag** [alchemy-fr/Phraseanet#3770]
Dear Phraseanet-developers,

I am just starting out with Phraseanet on my own vServer and used the Docker method to install your software.

During running "docker-compose up -d" I got the following messages about some abandoned repositories:

```
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.
Package zendframework/zend-eventmanager is abandoned, you should avoid using it. Use laminas/laminas-eventmanager instead.
Package zendframework/zend-code is abandoned, you should avoid using it. Use laminas/laminas-code instead.
Package guzzlehttp/streams is abandoned, you should avoid using it. No replacement was suggested.
Package guzzlehttp/ringphp is abandoned, you should avoid using it. No replacement was suggested.
Package hoa/core is abandoned, you should avoid using it. Use hoa/consistency instead.
Package silex/silex is abandoned, you should avoid using it. Use symfony/flex instead.
Package silex/web-profiler is abandoned, you should avoid using it. Use symfony/web-profiler-bundle instead.
Package sorien/silex-dbal-profiler is abandoned, you should avoid using it. No replacement was suggested.
Package sorien/silex-pimple-dumper is abandoned, you should avoid using it. No replacement was suggested.
```
This is just to let you know and definetely not complaining. Your software looks very interesting and powerful.

Is there any way I can help out with German documentation? I also spent a few months in France and also speak French.

Best regards from Wernigerode, Germany
Maik

**Comment by nmaillat** [comment]
Hello,
Thank you for your message!
Indeed, we know we have deprecated dependencies, we work on it But lot of our time is currently dedicated to work on a new stack and we prefer making the best efforts for this new one.
Concerning documentation:
-Phraseanet documentation is a git repository and when we began, we didn't plan to translate it in German but maybe the new one we do.
-For translations, we are currently moving our Weblate to a new infra. As soon as it's up, we will let you know so you can participate if you wish. We appreciate it! 
Best regards,
