### ISSUE TITLE
Having a hard time building the Docker images

### ISSUE THREAD

**Issue by trycoon** [alchemy-fr/Phraseanet#4155]
Cloning the repo and running:
`docker-compose build`

Gives me: 
 => ERROR [local/phraseanet-elasticsearch:4.1.6-rc4 internal] load metadata for docker.io/library/elasticsearch:2.4                                                                                     1.9s

The Elasticsearch:2.4 image does not exist, bumping to 2.4.1 in docker/elasticsearch/Dockerfile does fix this. But really 2.4 is six years old and I believe its no longer supported. We should migrate to newer versions!

Now I'm stuck with:

`#0 8.733 configure: error: Cannot find ldap libraries in /usr/lib/x86_64-linux-gnu/.
------
failed to solve: executor failed running [/bin/sh -c echo "BUILDING PHP PECL EXTENTIONS"     && ldconfig     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install -j$(nproc) gd     && docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/     && docker-php-ext-install -j$(nproc) ldap     && docker-php-ext-install zip exif iconv mbstring pcntl sockets xsl intl pdo_mysql gettext bcmath mcrypt     && mkdir -p /usr/src/php/ext/     && git clone --depth=1 https://github.com/kjdev/php-ext-jq.git /usr/src/php/ext/php-ext-jq     && docker-php-ext-install php-ext-jq     && pecl install         redis         amqp-1.9.3         zmq-beta         imagick-beta         xdebug-2.6.1     && docker-php-ext-enable redis amqp zmq imagick     && pecl clear-cache     && docker-php-source delete]: exit code: 1`

Is there some prerequisites missing or not documented?

**Comment by nmaillat** [comment]
we don't reproduce your issue based on informations you give  
try use it the prebuild image you can find here 
https://hub.docker.com/repository/docker/alchemyfr/phraseanet-elasticsearch
read the env or on readme for using Docker registry


If you want try our new project "Phrasea" using elasticsearch  7.11 version 
https://github.com/alchemy-fr/phrasea

**Comment by trycoon** [comment]
The Elastic-problem was solved by just stepping to 2.4.1, however the GD-library was the one failing my build. (maybe since I'm running on a Mac?).
