### ISSUE TITLE
Error message when getting docker images with 'docker-compose pull'

### ISSUE THREAD

**Issue by fvias** [alchemy-fr/Phraseanet#4183]
Hi,
My error message when I try to get docker images with 'docker-compose pull':
C:\Temp\alchemy-fr-Phraseanet-v4.1.5\Phraseanet>docker-compose pull
CreateFile C:\Temp\alchemy-fr-Phraseanet-v4.1.5\Phraseanet\docker-compose.yml:docker-compose.datastores.yml:docker-compose.tools.yml: The filename, directory name, or volume label syntax is incorrect.

Could you give me a feedback ?
Thanks

**Comment by nmaillat** [comment]
Hi,
You should check your Docker local configuration, have you test to pull another  Docker image like `docker pull nginx` ?

**Comment by fvias** [comment]
Hi,
I tried to pull the image you mentioned and it's working:

C:\Temp\alchemy-fr-Phraseanet-v4.1.5\Phraseanet>docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx
a603fa5e3b41: Pull complete
c39e1cda007e: Pull complete
90cfefba34d7: Pull complete
a38226fb7aba: Pull complete
62583498bae6: Pull complete
9802a2cfdb8d: Pull complete
Digest: sha256:e209ac2f37c70c1e0e9873a5f7231e91dcd83fdf1178d8ed36c2ec09974210ba
Status: Downloaded newer image for nginx:latest
docker.io/library/nginx:latest

C:\Temp\alchemy-fr-Phraseanet-v4.1.5\Phraseanet>

Thanks

**Comment by fvias** [comment]
Could you verify why it's not working with the Phraseanet package ?

**Comment by fvias** [comment]
Install ok, needs some customization :
https://domotikhome.blogspot.com/2021/10/installing-alchemy-phraseanet-dam-on.html

**Comment by nmaillat** [comment]
Hello Fvias,  many thank you for your documentation.
For information the typo in `ENV_SET_PHRASEANET_PROJECT_NAME` has been fixed in this commit
https://github.com/alchemy-fr/Phraseanet/commit/a914958a7c6c6aaa02716773f3a5694604b62b23
